### ISSUE TITLE
Missing files in WEB-INF?

### ISSUE THREAD

**Issue by dacount97** [writecodedrinkcoffee/vagrant-lemtl#2]
Trying to get this set up with no modifications, once the box comes up I get 500 errors trying to load pages.  In the catalina.out log, there are a bunch of error messages of not being able to find files.  One example from the logs:

Thu Mar 26 14:44:50 EDT 2015-825 write file:/var/www/sites/default/WEB-INF/lucee/context/templates/error/error-public.cfm
Thu Mar 26 14:44:50 EDT 2015-832 No such file or directory
java.io.IOException: No such file or directory

Really appreciate all the work you've done on this!

**Comment by dacount97** [comment]
I see this is the same as the previous issue mentioned.  I'll try reprovisioning, but the files that the CFservlet is trying to access don't exist in that folder.  I'll update on whether or not that fixes this issue.

**Comment by dacount97** [comment]
So, I changed the webroot owner and group to "tomcat7" and ran vagrant reload --provision, and that seemed to fix it.  I'm going to do a vagrant destroy and then call the box up again, see if it's just on the first run of vagrant up or whether it was the webroot owner.  There are way more files in the WEB-INF/lucee directory though, now that it's been re-provisioned.

**Comment by dacount97** [comment]
I've destroyed and re-created the vagrant box with the default files and it seems that lucee isn't getting properly unpacked in the first run of the script.  My WEB-INF does not contain all the files needed to run lucee.  I'll pick this up again tomorrow and see if you just have to re provision, or if you have to change the shared user first (which doesn't work on the initial call, virtualbox doesn't like the tomcat7 user trying to share that folder).

**Comment by mikesprague** [comment]
Thanks for all the info and follow-up about your issue. It definitely sounds like the same problem referenced in the chicken/egg section of [Mark Drew's article](http://blog.cmdbase.io/saving-railo-configurations/) as well as the [first reported issue here](https://github.com/mikesprague/vagrant-lemtl/issues/1). 

Until/if I am able to find a better resolution to this, I will document the need to re-provision with the tomcat7 user in the readme. 

The missing error template seems to be an issue with Lucee (dating back to Railo). I have seen this error not only in this project but in my [Heroku-based Lucee apps](https://github.com/mikesprague/lucee-heroku) and on several production servers of various OS configurations. Sorry I can't be more help there.

Regarding the WEB-INF folder... only the Lucee configuration files, Lucee lib (jar) files, and cfspreadsheet-related files are included; it is expected behavior for the rest of the contents to be generated.
